package com.adservio.cesco.config.mission;

import com.adservio.cesco.domain.OriginMission;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.stereotype.Component;

import java.util.Calendar;

@Component
public class OriginMissionProcessor implements ItemProcessor<OriginMission, OriginMission> {

    public OriginMissionProcessor() {
    }

    @Override
    public OriginMission process(OriginMission originMission) throws Exception {
        originMission.setId(null);//to make it generated by hibernate
        originMission.setActive(true);
        if (originMission.getDateDebut() == null)
            originMission.setDateDebut(new java.sql.Date(Calendar.getInstance().getTimeInMillis()));
        if (originMission.getDateFin() != null && originMission.getDateDebut() != null)
            if (originMission.getDateFin().after(new java.sql.Date(Calendar.getInstance().getTimeInMillis())))
                originMission.setActive(false);
        return originMission;
    }
}
