package com.adservio.cesco.config.station;

import com.adservio.cesco.domain.Station;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.stereotype.Component;

import java.util.Calendar;

@Component
public class StationItemProcessor implements ItemProcessor<Station, Station> {

    public StationItemProcessor() {
    }

    @Override
    public Station process(Station station) throws Exception {
        station.setId(null);//to make it generated by hibernate
        station.setActive(true);
        if (station.getDateDebut() == null)
            station.setDateDebut(new java.sql.Date(Calendar.getInstance().getTimeInMillis()));
        if (station.getDateFin() != null && station.getDateDebut() != null)
            if (station.getDateFin().after(new java.sql.Date(Calendar.getInstance().getTimeInMillis())))
                station.setActive(false);
        return station;
    }
}