package com.adservio.cesco.config.typeMission;

import com.adservio.cesco.domain.TypeMission;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.stereotype.Component;

import java.util.Calendar;

@Component
public class TypeMissionProcessor implements ItemProcessor<TypeMission, TypeMission> {
    public TypeMissionProcessor() {
    }

    @Override
    public TypeMission process(TypeMission typeMission) throws Exception {
        typeMission.setId(null);//to make it generated by hibernate
        typeMission.setActive(true);
        if (typeMission.getDateDebut() == null)
            typeMission.setDateDebut(new java.sql.Date(Calendar.getInstance().getTimeInMillis()));
        if (typeMission.getDateFin() != null && typeMission.getDateDebut() != null)
            if (typeMission.getDateFin().after(new java.sql.Date(Calendar.getInstance().getTimeInMillis())))
                typeMission.setActive(false);
        return typeMission;
    }
}
